# All endpoint constants that both the OpenChannel and GroupChannel
# resources share
BAN_USER = "/ban"
FREEZE = "/freeze"
LIST_BANNED_USERS = "/ban"
LIST_MUTED_USERS = "/mute"
MUTE_USER = "/mute"
UNBAN_USER = "/ban/{banned_user_id}"
UNMUTE_USER = "/mute/{muted_user_id}"
UPDATE_BAN = "/ban/{banned_user_id}"
VIEW_BAN = "/ban/{banned_user_id}"
VIEW_MUTE = "/mute/{muted_user_id}"

DELETE_MESSAGE = "/messages/{message_id}"
LIST_MESSAGES = "/messages"
MARK_AS_READ = "/messages/mark_as_read"
SEND_MESSAGE = "/messages"
UPDATE_MESSAGE = "/messages/{message_id}"
VIEW_MEMBER_UNNREAD_COUNT = "/messages/unread_count"
VIEW_MESSAGE = "/messages/{message_id}"
VIEW_MESSAGE_COUNT = "/messages/total_count"

CREATE_METADATA = "/metadata"
DELETE_METADATA = "/metadata"
UPDATE_METADATA = "/metadata"
VIEW_METADATA = "/metadata"

CREATE_METACOUNTER = "/metacounter"
DELETE_METACOUNTER = "/metacounter"
UPDATE_METACOUNTER = "/metacounter"
VIEW_METACOUNTER = "/metacounter"
